"""Minimal psycopg3 adapter exposing the tiny sqlite3-style surface that
server.py relies on, so the app can run unchanged against Postgres
(e.g. Vercel + Neon) instead of a local SQLite file.

server.py only ever uses ``conn.execute(sql, params)`` and
``conn.executescript(sql)``, with results consumed via ``.fetchone()`` /
``.fetchall()`` / ``.lastrowid``. This module reproduces exactly that.

Why a shim instead of rewriting 80+ call sites:
- Placeholders: SQLite uses ``?`` while psycopg uses ``%s``. Verified there
  are no ``?`` inside string literals and no ``%`` inside any SQL string in
  server.py, so a blind ``?`` -> ``%s`` replacement is safe.
- ``lastrowid``: Postgres has no implicit lastrowid, so we append
  ``RETURNING id`` to INSERTs (every table in the schema has an ``id`` PK)
  and expose the returned value as ``.lastrowid``.
- ``PRAGMA``: translated (table_info -> information_schema, foreign_keys ->
  no-op).
- ``IntegrityError``: psycopg's unique-violation is re-raised as
  ``sqlite3.IntegrityError`` so existing ``except sqlite3.IntegrityError``
  blocks keep working.
- DDL dialect: ``INTEGER PRIMARY KEY AUTOINCREMENT`` -> identity column and
  ``BLOB`` -> ``BYTEA`` inside executescript.
"""
from __future__ import annotations

import re
import sqlite3  # reused only for its IntegrityError type
import threading
from typing import Any, Sequence

import psycopg
from psycopg.rows import dict_row


_INSERT = re.compile(r"^\s*INSERT\b", re.IGNORECASE)
_RETURNING = re.compile(r"\bRETURNING\b", re.IGNORECASE)
_PRAGMA_TABLE_INFO = re.compile(
    r"^\s*PRAGMA\s+table_info\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*;?\s*$",
    re.IGNORECASE,
)
_PRAGMA_ANY = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)

_DDL_REPLACEMENTS = (
    (
        re.compile(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE),
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ),
    (re.compile(r"\bBLOB\b", re.IGNORECASE), "BYTEA"),
)


def _translate(sql: str) -> str:
    # qmark -> pyformat. Safe: no '?' inside string literals and no literal
    # '%' inside any SQL string in server.py (verified).
    return sql.replace("?", "%s")


def _translate_ddl(sql: str) -> str:
    out = sql
    for pat, repl in _DDL_REPLACEMENTS:
        out = pat.sub(repl, out)
    return out


class _Result:
    __slots__ = ("_rows", "lastrowid")

    def __init__(self, rows: list, lastrowid: Any) -> None:
        self._rows = rows
        self.lastrowid = lastrowid

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return list(self._rows)

    def __iter__(self):
        return iter(self._rows)


class PgConnection:
    """sqlite3.Connection look-alike backed by a single psycopg connection."""

    def __init__(self, dsn: str) -> None:
        self._conn = psycopg.connect(dsn, autocommit=True, row_factory=dict_row)
        self._lock = threading.Lock()

    def execute(self, sql: str, params: Sequence[Any] = ()) -> _Result:
        with self._lock:
            return self._execute_locked(sql, tuple(params or ()))

    def _execute_locked(self, sql: str, params: tuple) -> _Result:
        m = _PRAGMA_TABLE_INFO.match(sql)
        if m:
            cur = self._conn.execute(
                "SELECT column_name AS name FROM information_schema.columns "
                "WHERE table_schema = current_schema() AND table_name = %s",
                (m.group(1),),
            )
            return _Result(cur.fetchall(), None)
        if _PRAGMA_ANY.match(sql):
            # e.g. "PRAGMA foreign_keys = ON" -> Postgres enforces FKs anyway.
            return _Result([], None)

        query = _translate(sql)
        add_returning = bool(_INSERT.match(sql)) and not _RETURNING.search(sql)
        if add_returning:
            query = query.rstrip().rstrip(";") + " RETURNING id"

        try:
            cur = self._conn.execute(query, params)
        except psycopg.errors.IntegrityError as exc:
            raise sqlite3.IntegrityError(str(exc)) from exc

        if cur.description is None:
            return _Result([], None)
        rows = cur.fetchall()
        if add_returning:
            lastrowid = rows[0]["id"] if rows else None
            return _Result([], lastrowid)
        return _Result(rows, None)

    def executescript(self, script: str) -> None:
        body = _translate_ddl(script)
        with self._lock:
            for stmt in body.split(";"):
                if stmt.strip():
                    self._conn.execute(stmt)

    def close(self) -> None:
        self._conn.close()
