name: todo_sync_client
description: Offline-first Todo client for Android + Windows.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

